name: emergency_transcripts
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas=2.1.0
  - requests=2.31.0
  - spacy=3.6.0
  - tqdm=4.66.0
  - pip
  -   pip:
      - pydantic<2
      - usaddress==0.5.10
      - paramiko==3.2.0
      - runpod==1.7.13
      - gspread==5.7.2
      - oauth2client==4.1.3
      - python-dotenv==1.0.1
      - https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.6.0/en_core_web_sm-3.6.0-py3-none-any.whl
